### ISSUE TITLE
Style of DB models

### ISSUE THREAD

**Issue by art1415926535** [BoldinDmitry/s_soboy#1]
# What you need to pay attention
### FK naming
https://github.com/BoldinDmitry/s_soboy/blob/7cc53640400ea1007b7ef43b8e198f91fa9e6569/s_soboy/cafes/models.py#L20

https://github.com/BoldinDmitry/s_soboy/blob/7cc53640400ea1007b7ef43b8e198f91fa9e6569/s_soboy/cafes/models.py#L41

### Time fields naming 
https://github.com/BoldinDmitry/s_soboy/blob/7cc53640400ea1007b7ef43b8e198f91fa9e6569/s_soboy/cafes/models.py#L60

### Unnecessary space between model fields
https://github.com/BoldinDmitry/s_soboy/blob/7cc53640400ea1007b7ef43b8e198f91fa9e6569/s_soboy/cafes/models.py#L60-L62

# Read this:
  * [Советы по работе с ORM](https://articles.life4web.ru/rus/db-models/)
  * [Official coding style](https://docs.djangoproject.com/en/2.1/internals/contributing/writing-code/coding-style/#model-style)

**Comment by BoldinDmitry** [comment]
Here is a commit with improvements of models style code[https://github.com/BoldinDmitry/s_soboy/commit/df5ee553676950130a8c322e4f045ec40d52b453](url)
