### ISSUE TITLE
Why are tests.py empty?

### ISSUE THREAD

**Issue by art1415926535** [BoldinDmitry/s_soboy#2]
Create tests for each view. [It's easy with DRF!](https://www.django-rest-framework.org/api-guide/testing/#example)

**Comment by BoldinDmitry** [comment]
I wrote simple test check it. I hope it is correct.

**Comment by art1415926535** [comment]
Where are the tests for post, patch and delete requests?

**Comment by art1415926535** [comment]
You can make request using only the path in url:
e.g.
```python
response = self.client.get('/cafes/')
```

**Comment by BoldinDmitry** [comment]
I wrote new tests. Check it and say what do you think.
