### ISSUE TITLE
API filters

### ISSUE THREAD

**Issue by art1415926535** [BoldinDmitry/s_soboy#3]
Why can't frontend filter data from the API?
I know great library for this. [django-filter](https://django-filter.readthedocs.io/en/master/guide/rest_framework.html)

**Comment by BoldinDmitry** [comment]
Ok, thank you for your recommendation. I'll use it

**Comment by BoldinDmitry** [comment]
I pushed a new commit with Django filters, please, check it, and if something is wrong say me, please.
