### ISSUE TITLE
API: Objects ids

### ISSUE THREAD

**Issue by art1415926535** [BoldinDmitry/s_soboy#4]
The ID field must be made accessible by API. Some endpoints may require value of this field. 

https://github.com/BoldinDmitry/s_soboy/blob/7cc53640400ea1007b7ef43b8e198f91fa9e6569/s_soboy/cafes/serializers.py#L9

**Comment by BoldinDmitry** [comment]
Thanks, I added id field to AddressSerializer.
[https://github.com/BoldinDmitry/s_soboy/commit/5e963ef733bbaab5640c14bf6ecbe417bb993ecc](url)
